layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    - learn_git

social_media:
#   behance: your_username
#   dribbble: your_username
    facebook: Dantheman27c
#   hackerrank: your_username
    instagram: dantheman27c
#   keybase: your_username
    linkedin: daniel-clyde-530bb6170
#   mastodon: your_username
#   medium: your_username
#   stackoverflow: your_user_id
#   telegram: your_username
#   twitter: your_username
#   unsplash: your_username
#   vk: your_username
#   website: http://your_website_url
#   youtube: your_usernam

topics:
  - name: Typescript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png

  - name: Redux
    web_url: https://github.com/topics/redux
    image_url: https://redux.js.org/img/redux.svg

  - name: Angular
    web_url: https://github.com/topics/angular
    image_url: https://raw.githubusercontent.com/github/explore/49e13f12be05e7e3f3616bb7a5030d70b259f320/topics/angular/angular.png

  - name: NPM
    web_url: https://github.com/topics/npm
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/npm/npm.png

  - name: ExpressJS
    web_url: https://github.com/topics/express
    image_url: https://i.ytimg.com/vi/N24IyVTVzSs/maxresdefault.jpg

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Django
    web_url: https://github.com/topics/django
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/django/django.png

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://www.pngfind.com/pngs/m/105-1054207_learning-png-logo-machine-learning-png-transparent-png.png

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png
